import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  countQuestionitemsInText,
  computeQuestionCounts,
  renderQuestionCountsModule,
  findQbtTexFiles,
} from './count-questions.mjs';

describe('countQuestionitemsInText', () => {
  it('counts \\questionitem use-sites', () => {
    const tex = [
      '\\questionitem',
      'Some statement.',
      '\\questionitem',
      'Another.',
    ].join('\n');
    expect(countQuestionitemsInText(tex)).toBe(2);
  });

  it('ignores \\newcommand and \\renewcommand definitions', () => {
    const tex = [
      '\\newcommand{\\questionitem}{\\item}',
      '\\renewcommand{\\questionitem}{\\item}',
      '\\questionitem',
      'Real use.',
    ].join('\n');
    expect(countQuestionitemsInText(tex)).toBe(1);
  });

  it('returns 0 when there are no question items', () => {
    expect(countQuestionitemsInText('Nothing here.')).toBe(0);
  });
});

describe('computeQuestionCounts (temp fixture)', () => {
  /** @type {string} */
  let workdir;

  beforeEach(() => {
    workdir = mkdtempSync(join(tmpdir(), 'count-questions-'));
    // Lay out a minimal `<workdir>/tex/...` tree mimicking the real repo.
    const baseQbt = join(workdir, 'tex', 'further-maths', 'core-pure', 'topic-a', 'qbt');
    const baseSoln = join(workdir, 'tex', 'further-maths', 'core-pure', 'topic-a', 'soln');
    const baseQbtB = join(workdir, 'tex', 'further-maths', 'core-pure', 'topic-b', 'qbt');
    mkdirSync(baseQbt, { recursive: true });
    mkdirSync(baseSoln, { recursive: true });
    mkdirSync(baseQbtB, { recursive: true });
    writeFileSync(
      join(baseQbt, '_QBT__Topic_A.tex'),
      ['\\questionitem', 'q1', '\\questionitem', 'q2', '\\questionitem', 'q3'].join('\n'),
    );
    // Solns file should be SKIPPED by the QBT-only finder.
    writeFileSync(
      join(baseSoln, '_QBT___Solns__Topic_A.tex'),
      ['\\questionitem', 'soln-q1'].join('\n'),
    );
    writeFileSync(
      join(baseQbtB, '_QBT__Topic_B.tex'),
      ['\\questionitem', 'only-one'].join('\n'),
    );
  });

  afterEach(() => {
    rmSync(workdir, { recursive: true, force: true });
  });

  it('finds only QBT (non-Solns) tex files', () => {
    const files = findQbtTexFiles(join(workdir, 'tex'));
    expect(files).toHaveLength(2);
    expect(files.every((f) => /_QBT__[^/\\]+\.tex$/.test(f))).toBe(true);
    expect(files.some((f) => f.includes('_QBT___Solns'))).toBe(false);
  });

  it('returns sorted [/tex/...pdf, count] entries', () => {
    const entries = computeQuestionCounts(workdir);
    expect(entries).toEqual([
      ['/tex/further-maths/core-pure/topic-a/qbt/_QBT__Topic_A.pdf', 3],
      ['/tex/further-maths/core-pure/topic-b/qbt/_QBT__Topic_B.pdf', 1],
    ]);
  });

  it('returns [] when the tex root does not exist', () => {
    expect(computeQuestionCounts(join(workdir, 'no-such-dir'))).toEqual([]);
  });
});

describe('renderQuestionCountsModule', () => {
  it('renders a stable, byte-identical module for fixed input', () => {
    const out = renderQuestionCountsModule([
      ['/tex/a.pdf', 3],
      ['/tex/b.pdf', 7],
    ]);
    expect(out).toBe(
      [
        '// AUTO-GENERATED by scripts/count-questions.mjs — do not edit manually.',
        '// Regenerated on every `npm run build`, `npm run dev`, and `npm run check`.',
        'export const questionCounts: Record<string, number> = {',
        "  '/tex/a.pdf': 3,",
        "  '/tex/b.pdf': 7,",
        '};',
        '',
      ].join('\n'),
    );
  });

  it('renders an empty record when there are no entries', () => {
    const out = renderQuestionCountsModule([]);
    expect(out).toContain('export const questionCounts: Record<string, number> = {');
    expect(out).toMatch(/\{\n\};\n$/);
  });
});
