import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  findPdfFiles,
  hashFile,
  computeFileHashes,
  renderFileHashesModule,
} from './hash-assets.mjs';

describe('findPdfFiles (temp fixture)', () => {
  /** @type {string} */
  let workdir;

  beforeEach(() => {
    workdir = mkdtempSync(join(tmpdir(), 'hash-assets-'));
    const a = join(workdir, 'tex', 'topic-a', 'qbt');
    const aBuild = join(workdir, 'tex', 'topic-a', 'qbt', 'build');
    const aBuildAux = join(workdir, 'tex', 'topic-a', 'qbt', 'build', 'aux');
    const b = join(workdir, 'tex', 'topic-b', 'soln');
    mkdirSync(a, { recursive: true });
    mkdirSync(aBuild, { recursive: true });
    mkdirSync(aBuildAux, { recursive: true });
    mkdirSync(b, { recursive: true });
    writeFileSync(join(a, 'kept.pdf'), 'pdf-bytes-a');
    writeFileSync(join(aBuild, 'skipped.pdf'), 'should-not-appear');
    writeFileSync(join(aBuildAux, 'also-skipped.pdf'), 'should-not-appear');
    writeFileSync(join(b, 'kept-b.pdf'), 'pdf-bytes-b');
    // Non-PDF files are skipped.
    writeFileSync(join(a, 'kept.tex'), '\\documentclass{article}');
  });

  afterEach(() => {
    rmSync(workdir, { recursive: true, force: true });
  });

  it('skips files under build/ and aux/', () => {
    const files = findPdfFiles(join(workdir, 'tex'));
    expect(files).toHaveLength(2);
    expect(files.every((f) => f.endsWith('.pdf'))).toBe(true);
    expect(files.some((f) => f.includes('build'))).toBe(false);
    expect(files.some((f) => f.includes('aux'))).toBe(false);
  });

  it('returns [] when the dir does not exist', () => {
    expect(findPdfFiles(join(workdir, 'no-such-dir'))).toEqual([]);
  });
});

describe('hashFile + computeFileHashes', () => {
  /** @type {string} */
  let workdir;

  beforeEach(() => {
    workdir = mkdtempSync(join(tmpdir(), 'hash-assets-c-'));
    const a = join(workdir, 'tex', 'topic-a', 'qbt');
    mkdirSync(a, { recursive: true });
    writeFileSync(join(a, 'a.pdf'), 'aaa');
    writeFileSync(join(a, 'b.pdf'), 'bbb');
  });

  afterEach(() => {
    rmSync(workdir, { recursive: true, force: true });
  });

  it('hashFile returns 8-char hex md5 prefix', () => {
    const h = hashFile(join(workdir, 'tex', 'topic-a', 'qbt', 'a.pdf'));
    expect(h).toMatch(/^[0-9a-f]{8}$/);
    // md5("aaa") = 47bce5c74f589f4867dbd57e9ca9f808 → first 8 chars
    expect(h).toBe('47bce5c7');
  });

  it('computeFileHashes returns sorted [/tex/..., hash] entries', () => {
    const entries = computeFileHashes(workdir);
    expect(entries.map(([p]) => p)).toEqual([
      '/tex/topic-a/qbt/a.pdf',
      '/tex/topic-a/qbt/b.pdf',
    ]);
    expect(entries.every(([, h]) => /^[0-9a-f]{8}$/.test(h))).toBe(true);
  });
});

describe('renderFileHashesModule', () => {
  it('renders a stable, byte-identical module for fixed input', () => {
    const out = renderFileHashesModule([
      ['/tex/a.pdf', 'deadbeef'],
      ['/tex/b.pdf', 'cafef00d'],
    ]);
    expect(out).toBe(
      [
        '// AUTO-GENERATED by scripts/hash-assets.mjs — do not edit manually.',
        '// Regenerated on every `npm run build`, `npm run dev`, and `npm run check`.',
        'export const fileHashes: Record<string, string> = {',
        "  '/tex/a.pdf': 'deadbeef',",
        "  '/tex/b.pdf': 'cafef00d',",
        '};',
        '',
      ].join('\n'),
    );
  });
});
