/**
 * Hashes every deployed PDF under public/tex/ and writes
 * src/data/fileHashes.generated.ts, keyed by the /tex/... public URL path.
 * Run automatically via npm lifecycle hooks before build/dev/check.
 */

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');
const publicDir = join(repoRoot, 'public');

/** Recursively finds all deployed .pdf files, skipping build/aux directories. */
function findPdfFiles(dir) {
  const results = [];
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return results;
  }
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === 'build' || entry.name === 'aux') continue;
      results.push(...findPdfFiles(full));
    } else if (entry.name.endsWith('.pdf')) {
      results.push(full);
    }
  }
  return results;
}

const pdfFiles = findPdfFiles(join(publicDir, 'tex'));
const hashes = {};

for (const pdfPath of pdfFiles) {
  const content = readFileSync(pdfPath);
  const hash = createHash('md5').update(content).digest('hex').slice(0, 8);
  const rel = pdfPath.slice(publicDir.length).replace(/\\/g, '/');
  hashes[rel] = hash;
}

const entries = Object.entries(hashes).sort(([a], [b]) => a.localeCompare(b));

const lines = [
  '// AUTO-GENERATED by scripts/hash-assets.mjs — do not edit manually.',
  '// Regenerated on every `npm run build`, `npm run dev`, and `npm run check`.',
  'export const fileHashes: Record<string, string> = {',
  ...entries.map(([path, hash]) => `  '${path}': '${hash}',`),
  '};',
  '',
];

const outPath = join(repoRoot, 'src', 'data', 'fileHashes.generated.ts');
writeFileSync(outPath, lines.join('\n'), 'utf-8');
console.log(`[hash-assets] ${entries.length} entries written to src/data/fileHashes.generated.ts`);
